AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  NutritionTrackerAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.9
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseURL
          JWT_SECRET_KEY: !Ref JWTSecretKey
          ALLOWED_ORIGINS: !Ref AllowedOrigins
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            Cors:
              AllowMethods: "'*'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"

Parameters:
  DatabaseURL:
    Type: String
    Description: PostgreSQL database connection string
    NoEcho: true
  
  JWTSecretKey:
    Type: String
    Description: JWT secret key for authentication
    NoEcho: true
  
  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins
    Default: "http://localhost:3000,http://localhost:5173"

Outputs:
  NutritionTrackerApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
