"""Add dietary preferences to user profile

Revision ID: 577b54cb0f45
Revises: 7fdae63cf520
Create Date: 2025-11-04 11:38:06.582506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577b54cb0f45'
down_revision: Union[str, Sequence[str], None] = '7fdae63cf520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('dietary_preference', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('budget_range', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_cuisine', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_cuisine')
    op.drop_column('user_profiles', 'budget_range')
    op.drop_column('user_profiles', 'dietary_preference')
    # ### end Alembic commands ###
